#!/bin/bash

SEP=${SEP:-"+"}

version=$(cat VERSION || echo dev | sed -e 's/^v//g')
exact_tag=$(git describe --exact-match 2>/dev/null | sed -e 's/^v//g' || echo '')

last_tag=$(git describe --tags --abbrev=0 2>/dev/null)
commits=$(git log --oneline "${last_tag}"..HEAD | wc -l | tr -d ' ')
revision=$(git rev-parse --short HEAD || echo unknown)

if echo "${exact_tag}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+$"; then
    echo "$exact_tag"
    exit 0
fi

if echo "${exact_tag}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$"; then
    echo "$exact_tag"
    exit 0
fi

if echo "${exact_tag}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$"; then
    echo "$exact_tag"
    exit 0
fi

if [ "$commits" -eq 0 ]; then
    rc_regex="\-rc([0-9]+)$"
    if [ -n "${last_tag}" ]; then
        if [ -n "${RCTOBUILD}" ]; then
            if echo "$last_tag" | grep -qE "\-rc[0-9]+$"; then
                if [[ $last_tag =~ $rc_regex ]]
                then
                    revision="${BASH_REMATCH[1]}"
                    echo "${last_tag//v/}" | sed "s/-rc${revision}/${SEP}${revision}/g"
                    exit 0
                fi
            fi
        fi
        echo "${last_tag//v/}"
        exit 0
    fi
fi

if [ -z "${NOREV}" ]; then
    echo "${version}${SEP}${commits}-g${revision}"
else
    echo "${version}${SEP}${commits}"
fi